sudo ln -s ../ALTAdRevenue.h
sudo ln -s ../ALTAttribution.h
sudo ln -s ../ALTConfig.h
sudo ln -s ../ALTEvent.h
sudo ln -s ../ALTEventFailure.h
sudo ln -s ../ALTEventSuccess.h
sudo ln -s ../ALTLinkResolution.h
sudo ln -s ../ALTLogger.h
sudo ln -s ../ALTSessionFailure.h
sudo ln -s ../ALTSessionSuccess.h
sudo ln -s ../ALTSubscription.h
sudo ln -s ../ALTThirdPartySharing.h
sudo ln -s ../Alltrack.h