on:
  push:
    branches:
      - refs/tags/*
name: Build framework
jobs:
  static:
    name: Build static SDK
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          mkdir -p frameworks/static
          xcodebuild -target AlltrackStatic -configuration Release clean build

          mkdir AlltrackSdkStatic
          mv frameworks/static/* AlltrackSdkStatic
          zip -ry AlltrackSdkStatic.framework.zip AlltrackSdkStatic/*
      - name: Upload files
        uses: actions/upload-artifact@v2
        with:
          name: static_framework
          path: AlltrackSdkStatic.framework.zip
  tvOS:
    name: Build Static tvOS SDK
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Universal tvOS SDK
        run: |
          mkdir -p frameworks/static_tvos
          xcodebuild -configuration Release -target AlltrackSdkTv -arch x86_64 -sdk appletvsimulator clean build
          xcodebuild -configuration Release -target AlltrackSdkTv -arch arm64 -sdk appletvos build
          cp -Rv build/Release-appletvos/AlltrackSdkTv.framework frameworks/static_tvos
          lipo -create -output frameworks/static_tvos/AlltrackSdkTv.framework/AlltrackSdkTv build/Release-appletvos/AlltrackSdkTv.framework/AlltrackSdkTv build/Release-appletvsimulator/AlltrackSdkTv.framework/AlltrackSdkTv

          mkdir AlltrackSdkTvStatic
          mv frameworks/static_tvos/* AlltrackSdkTvStatic
          zip -ry AlltrackSdkTvStatic.framework.zip AlltrackSdkTvStatic/*
      - name: Upload files
        uses: actions/upload-artifact@v2
        with:
          name: universal_tvos
          path: AlltrackSdkTvStatic.framework.zip

  dynamic_ios_tvos:
    name: Build dynamic iOS and tvOS targets with Carthage
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Carthage
        run: |
          brew install carthage
      - name: Build dynamic framework
        run: |
          mv Alltrack.xcodeproj/xcshareddata/xcschemes/AlltrackSdkIm.xcscheme \
            Alltrack.xcodeproj/xcshareddata/xcschemes/AlltrackSdkWebBridge.xcscheme .
          carthage build --no-skip-current
          
          mkdir AlltrackSdkDynamic
          mv Carthage/Build/iOS/* AlltrackSdkDynamic
          zip -ry AlltrackSdkDynamic.framework.zip AlltrackSdkDynamic/*

          mkdir AlltrackSdkTvDynamic
          mv Carthage/Build/tvOS/* AlltrackSdkTvDynamic
          zip -ry AlltrackSdkTvDynamic.framework.zip AlltrackSdkTvDynamic/*
      - name: Upload iOS
        uses: actions/upload-artifact@v2
        with:
          name: dynamic_ios
          path: AlltrackSdkDynamic.framework.zip
      - name: Upload tvOS
        uses: actions/upload-artifact@v2
        with:
          name: dynamic_tvos
          path: AlltrackSdkTvDynamic.framework.zip

  dynamic_imessage:
    name: Build dynamic iMessage target with Carthage
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Carthage
        run: |
          brew install carthage
      - name: Build dynamic framework
        run: |
          mv Alltrack.xcodeproj/xcshareddata/xcschemes/*.xcscheme .
          mv AlltrackSdkIm.xcscheme Alltrack.xcodeproj/xcshareddata/xcschemes

          carthage build --no-skip-current
          
          mkdir AlltrackSdkImDynamic
          mv Carthage/Build/iOS/* AlltrackSdkImDynamic
          zip -ry AlltrackSdkIm.framework.zip AlltrackSdkImDynamic/*
      - name: Upload framework
        uses: actions/upload-artifact@v2
        with:
          name: dynamic_imessage
          path: AlltrackSdkIm.framework.zip

  dynamic_webbridge:
    name: Build dynamic WebBridge target with Carthage
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Carthage
        run: |
          brew install carthage
      - name: Build dynamic framework
        run: |
          mv Alltrack.xcodeproj/xcshareddata/xcschemes/*.xcscheme .
          mv AlltrackSdkWebBridge.xcscheme Alltrack.xcodeproj/xcshareddata/xcschemes

          carthage build --no-skip-current
          mkdir AlltrackSdkWebBridgeDynamic
          mv Carthage/Build/iOS/* AlltrackSdkWebBridgeDynamic
          zip -ry AlltrackSdkWebBridge.framework.zip AlltrackSdkWebBridgeDynamic/*
      - name: Upload framework
        uses: actions/upload-artifact@v2
        with:
          name: dynamic_webbridge
          path: AlltrackSdkWebBridge.framework.zip

  release:
    name: Create new release and upload assets
    runs-on: ubuntu-latest
    needs: [static, tvOS, dynamic_ios_tvos, dynamic_imessage, dynamic_webbridge]
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Version ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Download all frameworks
        uses: actions/download-artifact@v2
        with:
          path: frameworks
          
      - name: Upload static framework
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: frameworks/static_framework/AlltrackSdkStatic.framework.zip
          asset_name: AlltrackSdkStatic.framework.zip
          asset_content_type: application/zip
          
      - name: Upload tvOS framework
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: frameworks/universal_tvos/AlltrackSdkTvStatic.framework.zip
          asset_name: AlltrackSdkTvStatic.framework.zip
          asset_content_type: application/zip
          
      - name: Upload dynamic iOS framework
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: frameworks/dynamic_ios/AlltrackSdkDynamic.framework.zip
          asset_name: AlltrackSdkDynamic.framework.zip
          asset_content_type: application/zip
          
      - name: Upload dynamic tvOS framework
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: frameworks/dynamic_tvos/AlltrackSdkTvDynamic.framework.zip
          asset_name: AlltrackSdkTvDynamic.framework.zip
          asset_content_type: application/zip
          
      - name: Upload dynamic iMessage framework
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: frameworks/dynamic_imessage/AlltrackSdkIm.framework.zip
          asset_name: AlltrackSdkIm.framework.zip
          asset_content_type: application/zip
          
      - name: Upload dynamic WebBridge framework
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: frameworks/dynamic_webbridge/AlltrackSdkWebBridge.framework.zip
          asset_name: AlltrackSdkWebBridge.framework.zip
          asset_content_type: application/zip

